export const mockEmployees = [
  {
    id: 'emp_1',
    name: 'Rahul Sharma',
    email: 'rahul.sharma@peoplepay360.com',
    phone: '+91 98765 43210',
    address: 'Mumbai, Maharashtra',
    department: 'Engineering',
    position: 'Software Developer',
    manager: 'Amit Patel',
    joiningDate: '2023-01-15',
    status: 'Active',
    avatar: 'R',
    bankName: 'HDFC Bank',
    bankAccount: 'xxxx-xxxx-1234',
    ifsc: 'HDFC0001234',
    emergencyContact: 'Sneha Sharma (+91 98765 00000)',
  },
  {
    id: 'emp_2',
    name: 'Amit Patel',
    email: 'amit.patel@peoplepay360.com',
    phone: '+91 98765 43211',
    address: 'Ahmedabad, Gujarat',
    department: 'Engineering',
    position: 'Engineering Manager',
    manager: 'Neha Shah',
    joiningDate: '2021-06-01',
    status: 'Active',
    avatar: 'A',
    bankName: 'ICICI Bank',
    bankAccount: 'xxxx-xxxx-5678',
    ifsc: 'ICIC0005678',
    emergencyContact: 'Raj Patel (+91 98765 11111)',
  },
  {
    id: 'emp_3',
    name: 'Neha Shah',
    email: 'neha.shah@peoplepay360.com',
    phone: '+91 98765 43212',
    address: 'Pune, Maharashtra',
    department: 'Human Resources',
    position: 'HR Manager',
    manager: 'CEO',
    joiningDate: '2022-03-10',
    status: 'Active',
    avatar: 'N',
    bankName: 'SBI',
    bankAccount: 'xxxx-xxxx-9012',
    ifsc: 'SBIN0009012',
    emergencyContact: 'Kunal Shah (+91 98765 22222)',
  },
  {
    id: 'emp_4',
    name: 'Priya Mehta',
    email: 'priya.mehta@peoplepay360.com',
    phone: '+91 98765 43213',
    address: 'Delhi',
    department: 'Sales',
    position: 'Sales Executive',
    manager: 'Ravi Kumar',
    joiningDate: '2023-11-05',
    status: 'Active',
    avatar: 'P',
    bankName: 'Axis Bank',
    bankAccount: 'xxxx-xxxx-3456',
    ifsc: 'UTIB0003456',
    emergencyContact: 'Aman Mehta (+91 98765 33333)',
  },
  {
    id: 'emp_5',
    name: 'Nimesh Patel',
    email: 'nimesh.patel@peoplepay360.com',
    phone: '+91 98765 43214',
    address: 'Surat, Gujarat',
    department: 'Finance',
    position: 'Accountant',
    manager: 'Vikram Singh',
    joiningDate: '2024-02-20',
    status: 'Inactive',
    avatar: 'N',
    bankName: '',
    bankAccount: '',
    ifsc: '',
    emergencyContact: 'Reena Patel (+91 98765 44444)',
  },
];

export const DEPARTMENTS = ['Engineering', 'Human Resources', 'Finance', 'Sales', 'Marketing'];
export const POSITIONS = ['Software Developer', 'Engineering Manager', 'HR Manager', 'Accountant', 'Sales Executive', 'UI/UX Designer', 'Product Manager'];
export const STATUSES = ['Active', 'Inactive', 'Archived'];
